[package]
name = "ds-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = ["derive", "cargo"] }
lazy_static = "1.4.0"
regex = "1.8.3"

[[bin]]
name = "ds"
path = "src/main.rs"